# Generated by Django 6.0 on 2026-01-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fa-book)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('address', models.TextField()),
                ('phone1', models.CharField(max_length=15, verbose_name='Primary Phone')),
                ('phone2', models.CharField(blank=True, max_length=15, verbose_name='Secondary Phone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('about_text', models.TextField(verbose_name='About Us')),
                ('mission', models.TextField(blank=True, verbose_name='Our Mission')),
                ('vision', models.TextField(blank=True, verbose_name='Our Vision')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Information',
            },
        ),
    ]
