# Generated by Django 6.0 on 2026-01-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name="Student's Full Name")),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('applying_for_class', models.CharField(choices=[('nursery', 'Nursery'), ('lkg', 'LKG'), ('ukg', 'UKG'), ('class1', 'Class 1'), ('class2', 'Class 2'), ('class3', 'Class 3'), ('class4', 'Class 4'), ('class5', 'Class 5'), ('class6', 'Class 6'), ('class7', 'Class 7'), ('class8', 'Class 8')], max_length=20, verbose_name='Applying for Class')),
                ('previous_school', models.CharField(blank=True, max_length=200, verbose_name='Previous School (if any)')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('guardian_phone', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('alternate_phone', models.CharField(blank=True, max_length=15, verbose_name='Alternate Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('message', models.TextField(blank=True, verbose_name='Any Message/Query')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Admin Notes')),
            ],
            options={
                'verbose_name': 'Admission Inquiry',
                'verbose_name_plural': 'Admission Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
