# Generated by Django 6.0 on 2026-01-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important for highlight')),
                ('attachment', models.FileField(blank=True, help_text='PDF or document attachment', null=True, upload_to='notices/')),
            ],
            options={
                'ordering': ['-is_important', '-date_posted'],
            },
        ),
    ]
