# Generated by Django 5.1.5 on 2026-01-19 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-is_important', '-date_posted'], 'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF or document (optional)', null=True, upload_to='notices/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(help_text='Detailed notice content'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Notice date (editable)'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on website'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Highlight this notice'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(help_text='Notice title', max_length=200),
        ),
    ]
