# Generated by Django 5.1.5 on 2026-03-14 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('admission_date', models.DateField()),
                ('roll_number', models.PositiveIntegerField(help_text='Roll number within the class')),
                ('is_active', models.BooleanField(default=True, help_text='Currently studying in this school')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.academicclass', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['academic_class__order', 'academic_class__name', 'roll_number'],
                'unique_together': {('academic_class', 'roll_number')},
            },
        ),
    ]
