# Generated by Django 5.1.5 on 2026-03-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(blank=True, help_text='Roll number within the class', null=True),
        ),
    ]
